### ISSUE TITLE
Bifixer is stuck

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bitextor#183]
**Describe the bug**
My bitextor stay at this point :  
```
[Tue Oct 20 14:31:03 2020]
Finished job 11.
27 of 33 steps (82%) done

[Tue Oct 20 14:31:03 2020]
rule bifixer:
    input: /home/**/bitextor/french/atos.net/transient/atos/hunalign.segclean.xz
    output: /home/**/bitextor/french/atos.net/transient/atos/hunalign.bifixer.xz
    jobid: 10
    wildcards: prefix=/home/**/bitextor/french/atos.net/transient/atos/hunalign

```
I got the issue for a large amount of website.
When I interrupt it it says that it is waiting for handshake ?
```
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
````

**To Reproduce**
In docker with synthok segmenter install
my conf : 
```
bitextor: /opt/bitextor/
hosts: ["atos.net"]

permanentDir: /home/**/bitextor/french/atos.net
transientDir: /home/**/bitextor/french/atos.net/transient
dataDir: /home/**/bitextor/french/atos.net/data
temp: /home/**/bitextor/french/atos.net/transient
lang1: en
lang2: fr

crawler: wget
crawlFileTypes: "html,pdf"

sentenceSplitters: {
 'en': '/usr/bin/python3 -m syntok.segmenter',
 'fr': '/usr/bin/python3 -m syntok.segmenter'
}

documentAligner: DIC
dic: /home/**/dev/dics/bitextor_en-fr.1grams.dic

bicleaner: /home/**/bitextor/bicleaner_model/en-fr/en-fr.yaml
bicleanerThreshold: 0.5
bicleanerCacheWithSents: true

bifixer: true
elrc: true
tmx: false
profiling: true
```

It sometiimes works fine when I set `bicleanerCacheWithSents` to `false`

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Last Docker

**Comment by jgcb00** [comment]
So in my search for a solution, I found out that this error append very often but sometimes it doesn't and with the same configuration file it can succeed or not.
It is not link with bicleaner as it is also struggling without.
Here is the complete Traceback : 
```
Traceback (most recent call last):
  File "/opt/bitextor/bifixer/bifixer/bifixer.py", line 235, in <module>
    main(args)  # Running main program
  File "/opt/bitextor/bifixer/bifixer/bifixer.py", line 227, in main
    perform_fixing(args)
  File "/opt/bitextor/bifixer/bifixer/bifixer.py", line 211, in perform_fixing
    fix_sentences(args)
  File "/opt/bitextor/bifixer/bifixer/bifixer.py", line 119, in fix_sentences
    source_segmenter = segmenter.NaiveSegmenter(args.srclang, args.segmenter)
  File "/opt/bitextor/bifixer/bifixer/segmenter.py", line 155, in __init__
    self.segmenter = NLTKSegmenter(lang)
  File "/opt/bitextor/bifixer/bifixer/segmenter.py", line 73, in __init__
    nltk.download('punkt', quiet=True)
  File "/usr/local/lib/python3.6/dist-packages/nltk/downloader.py", line 787, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/local/lib/python3.6/dist-packages/nltk/downloader.py", line 636, in incr_download
    info = self._info_or_id(info_or_id)
  File "/usr/local/lib/python3.6/dist-packages/nltk/downloader.py", line 609, in _info_or_id
    return self.info(info_or_id)
  File "/usr/local/lib/python3.6/dist-packages/nltk/downloader.py", line 1019, in info
    self._update_index()
  File "/usr/local/lib/python3.6/dist-packages/nltk/downloader.py", line 962, in _update_index
    ElementTree.parse(urlopen(self._url)).getroot()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1442, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by lpla** [comment]
Looks like an HTTP connection issue when NLTK tries to download punctuation models, not a Bitextor or related code issue. Check this line from your traceback:


```
  File "/opt/bitextor/bifixer/bifixer/segmenter.py", line 73, in __init__
    nltk.download('punkt', quiet=True)
```

Try to run `nltk.download('punkt', quiet=True)` in a Python console using the same environment as Bitextor. If the issue continues, check if that issue is documented in the NLTK repository, as we weren’t able to reproduce it.

**Comment by jgcb00** [comment]
Hi, thank you very much for your help
Indeed it was a nltk issue solve by adding in `/opt/bitextor/bifixer/bifixer/segmenter.py` : 
```
import signal

---

def timeout(signum, frame):
    raise myException

class NLTKSegmenter:
    def __init__(self, lang):
        try:
            nltk.data.find('tokenizer/punkt')
        except:
            result = None
            while result is None:
                signal.signal(signal.SIGALRM, timeout)
                signal.alarm(3)
                try:
                    result = nltk.download('punkt', quiet=True)
                except:
                    pass

            #nltk.download('punkt', quiet=True)
```
I will close the issue, thank you very much for your help !

**Comment by jgcb00** [comment]
I reopen the issue as my previous solution isn't 100% working.

in `/opt/bitextor/bifixer/bifixer/segmenter.py` :
```
nltk.data.find('tokenizer/punkt')
```
never works.  Following error : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/nltk/data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizer/punkt

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```
While I've got in `/root/nltk_data/tokenizer following files : 
```
.
└── tokenizers
    ├── punkt
    │   ├── czech.pickle
    │   ├── danish.pickle
    │   ├── dutch.pickle
    │   ├── english.pickle
    │   ├── estonian.pickle
    │   ├── finnish.pickle
    │   ├── french.pickle
    │   ├── german.pickle
    │   ├── greek.pickle
    │   ├── italian.pickle
    │   ├── norwegian.pickle
    │   ├── polish.pickle
    │   ├── portuguese.pickle
    │   ├── PY3
    │   │   ├── czech.pickle
    │   │   ├── danish.pickle
    │   │   ├── dutch.pickle
    │   │   ├── english.pickle
    │   │   ├── estonian.pickle
    │   │   ├── finnish.pickle
    │   │   ├── french.pickle
    │   │   ├── german.pickle
    │   │   ├── greek.pickle
    │   │   ├── italian.pickle
    │   │   ├── norwegian.pickle
    │   │   ├── polish.pickle
    │   │   ├── portuguese.pickle
    │   │   ├── README
    │   │   ├── russian.pickle
    │   │   ├── slovene.pickle
    │   │   ├── spanish.pickle
    │   │   ├── swedish.pickle
    │   │   └── turkish.pickle
    │   ├── README
    │   ├── russian.pickle
    │   ├── slovene.pickle
    │   ├── spanish.pickle
    │   ├── swedish.pickle
    │   └── turkish.pickle
    └── punkt.zip
```
I got the right folder search in `nltk.data.find`

So as it always try to download, I got my previous issue.

My solution for now wich is not perfect at all is to comment the try and except part wich contains `nltk.data.find` and the `nltk.download` as I'm sure that their are successfully load.

**Comment by ZJaume** [comment]
Hi,

I've pushed a couple of commits to bifixer master in order to solve, or at least mitigate these things.

```
nltk.data.find('tokenizer/punkt')
```
Had a typo, it is `tokenizers`. Also, the code you attached, @jgcb00, has been added to perform timeout and retry when downloading.

Please, pull from master and check if the issue has solved to you.

**Comment by lpla** [comment]
Fixed in master branch and development branches as bifixer submodule has been updated. Closing.

**Comment by cgr71ii** [comment]
This issue is still happening. Now the problem is that, when you have to download `punkt` (only the first time thanks to fixed `nltk.data.find('tokenizers/punkt')`), there is a timeout of 5 seconds which, if not downloaded within this interval, the download will reset. In the case of a fast connection, you will reset the download until, luckily, you will successfully download the file and you won't even notice that bifixer kept stuck for a few seconds/minutes. In the case of an average/slow connection, this connection will be looping indefinitely.

The problem is in the file `bifixer/segmenter.py`, concretely at line `signal.alarm(5)`. I think that 5 seconds is not enought, and i guess that this value is low in order to prevent losing time if the download do not start, but in the case that it did start, this will stop and reset the download of the file.

This problem arised while i was checking an isolated Conda environment, but i've checked that this also is happening in a normal environment. Even i've tested changing this value and is totally dependent of the own connection speed/bandwidth. And not only so, but the `nltk` servers might be slow in a moment where they receive lots of requests. This value should be higher in order to avoid this problem.

**Comment by ZJaume** [comment]
Pushed https://github.com/bitextor/bifixer/commit/3f357d4916130810767655919a62ceac3d887559
