### ISSUE TITLE
bitextor-dir2warc.py error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#66]
echo "./Diskay_termeszettudosok.html" | $BITEXTOR/bitextor-dir2warc.py
Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/bitextor-dir2warc.py", line 33, in <module>
    dvalue=parse(date.decode("utf8")).strftime('%Y-%m-%dT%H:%M:%SZ')
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '<!-- Mirrored from regi.oszk.hu/hun/kiallit/virtualis/Ex_libris_virtualis_kiallitas/Diskay_termeszettudosok.htm, Thu, 17 Nov 2016 09:09:53 GMT')
hieu@brodie:~/workspace/experiment/issues/para

[Diskay_termeszettudosok.html.gz](https://github.com/bitextor/bitextor/files/2713559/Diskay_termeszettudosok.html.gz)

**Comment by mespla** [comment]
Fixed by 8db36f8fc2768e1d960cc5121c1df2dcf2f4a1b6

**Comment by hieuhoang** [comment]
still a problem with this file

Wondering if it's better to use the file creation (not last modified) date, rather than try to parse the html
   ls -lct /mnt/tmp/downloaded.gerlo.hu.RJl4h4/gerlo.hu/hvall/enci/religion_welbourn_def.html 
-rw-r--r-- 1 hieu hieu 27050 Dec 28 18:14 /mnt/tmp/downloaded.gerlo.hu.RJl4h4/gerlo.hu/hvall/enci/religion_welbourn_def.html

[religion_welbourn_def.zip](https://github.com/bitextor/bitextor/files/2715823/religion_welbourn_def.zip)
